# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c9f2b67bfbfb423ebc3c4b33a8ac144a1294ab9b9bde1e3ce4afedf6a5e5338fd045375126b3899f665ffb108a28016defc5a1b6993c019c1031fc844b628c28

test:
  secret_key_base: 28c006b698128adcff66aef7c0f889c7464d81692000eeb18e3e7a7b8f1b6298599601a1a80a46db7d2e127b34b87c944901e0a427302406347423d3c94d9e48

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
